version: "3.2"

volumes:
  db:

services:
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Berlin
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_SMTP_USER=cadviewer
      - MAILDEV_SMTP_PASSWORD=cadviewer
    ports:
      - "1080:1080"
      - "8025:1025"

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=visualquery
      - MYSQL_USER=visualquery
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080

  cadviewer_node:
    build: .
    #    platform: linux/arm64/v8
    platform: linux/amd64
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/nodejs/cadviewer-conversion-server
      - /nodejs/cadviewer-conversion-server/node_modules
